spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    user: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      format_sql: true
      hbm2ddl:
      auto: validate

server:
  port: 8888

keycloak:
  realm: notebook-realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: notebook-api
  credentials.secret: 9f81b925-d1d8-455c-939a-0136905236d9
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
